apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: github-runner-dev
  template:
    metadata:
      labels:
        app: github-runner-dev
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - gserver
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: github-runner-dev
        image: ghcr.io/glauciolabs/github-runner:v0.1.0-dev
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: github-runner-secrets-dev
        env:
        - name: GITHUB_URL
          valueFrom:
            secretKeyRef:
              name: github-runner-secrets-dev
              key: GITHUB_URL
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-secrets-dev
              key: RUNNER_TOKEN
        - name: RUNNER_GROUP
          valueFrom:
            secretKeyRef:
              name: github-runner-secrets-dev
              key: RUNNER_GROUP
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: dotnet
          value: "v10.0.110"
        - name: openjdk
          value: "v25.0.3"
        - name: nodejs
          value: "v26.6.0"
        - name: npm
          value: "v11.18.0"
        - name: yarn
          value: "v1.22.22"
        - name: snyk-cli
          value: "v1.1307.3"
        - name: argocd-cli
          value: "v3.5.0"
        - name: maven
          value: "v3.9.12"
        - name: kubectl
          value: "v1.36.3"
        - name: helm
          value: "v4.2.3"
        - name: golang-go
          value: "v1.26.0"
        - name: python
          value: "v3.14.4"
        - name: poetry
          value: "v2.4.1"
        - name: trivy
          value: "0.73.0"
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        resources:
          limits:
            cpu: "400m"
            memory: "2048Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
      - name: dind
        image: docker:dind
        securityContext:
          privileged: true
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
      volumes:
      - name: dind-storage
        emptyDir: {}
